package bandbuddy.testit;
// Generated by ComTest BEGIN
import java.util.*;
import java.io.IOException;
import fi.jyu.mit.ohj2.VertaaTiedosto;
import bandbuddy.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.04.19 17:36:40 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class GenretTest {



  // Generated by ComTest BEGIN
  /** testHGenre59 */
  @Test
  public void testHGenre59() {    // Genret: 59
    Genret i = new Genret(); 
    Genre a = new Genre("EDM"); 
    a.rekisteroi(); 
    i.lisaa(a); 
    Genre b = new Genre("Folk"); 
    b.rekisteroi(); 
    i.lisaa(b); 
    Genre c = new Genre("Metal"); 
    c.rekisteroi(); 
    i.lisaa(c); 
    assertEquals("From: Genret line: 70", 3, i.getLkm()); 
    assertEquals("From: Genret line: 71", "ei toimi", i.hGenre(-1)); 
    assertEquals("From: Genret line: 72", "EDM", i.hGenre(1)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta101 
   * @throws IOException when error
   */
  @Test
  public void testLueTiedostosta101() throws IOException {    // Genret: 101
    VertaaTiedosto.kirjoitaTiedosto("testi.dat", ";gid|genre|\n1|Jazz|\n2|Rock|\n3|Metal|\n4|Pop|\n5|EDM|\n"); 
    Genret testiGenreLuokka = new Genret(); 
    testiGenreLuokka.setLuettavaTiedosto("testi.dat"); 
    testiGenreLuokka.lueTiedostosta(); 
    VertaaTiedosto.tuhoaTiedosto("testi.dat"); 
    assertEquals("From: Genret line: 110", 5, testiGenreLuokka.getLkm()); 
    assertEquals("From: Genret line: 111", "Jazz", testiGenreLuokka.hGenre(1)); 
    assertEquals("From: Genret line: 112", "Rock", testiGenreLuokka.hGenre(2)); 
    assertEquals("From: Genret line: 113", "Metal", testiGenreLuokka.hGenre(3)); 
    assertEquals("From: Genret line: 114", "Pop", testiGenreLuokka.hGenre(4)); 
    assertEquals("From: Genret line: 115", "EDM", testiGenreLuokka.hGenre(5)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIterator164 */
  @Test
  public void testIterator164() {    // Genret: 164
    Genret genret = new Genret(); 
    Genre a = new Genre("Rock"); genret.lisaa(a); 
    Genre b = new Genre("Prog"); genret.lisaa(b); 
    Genre c = new Genre("Pop"); genret.lisaa(c); 
    Iterator<Genre> i2=genret.iterator(); 
    assertEquals("From: Genret line: 174", a, i2.next()); 
    assertEquals("From: Genret line: 175", b, i2.next()); 
    assertEquals("From: Genret line: 176", c, i2.next()); 
    try {
    assertEquals("From: Genret line: 177", b, i2.next()); 
    fail("Genret: 177 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}