package bandbuddy.testit;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import bandbuddy.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.04.18 22:47:01 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class GenreTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi62 */
  @Test
  public void testRekisteroi62() {    // Genre: 62
    Genre testigenre1 = new Genre("djent"); 
    testigenre1.rekisteroi(); 
    assertEquals("From: Genre line: 65", 1, testigenre1.getTunnusNro()); 
    Genre testigenre2 = new Genre("rock"); 
    testigenre2.rekisteroi(); 
    assertEquals("From: Genre line: 68", 2, testigenre2.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString92 */
  @Test
  public void testToString92() {    // Genre: 92
    Genre testigenre3 = new Genre("Psytrance"); 
    testigenre3.rekisteroi(); 
    assertEquals("From: Genre line: 95", "3|Psytrance|", testigenre3.toString()); 
    Genre testigenre4 = new Genre(); 
    assertEquals("From: Genre line: 97", "0||", testigenre4.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse110 */
  @Test
  public void testParse110() {    // Genre: 110
    Genre testigenre5 = new Genre("EDM"); 
    testigenre5.rekisteroi(); 
    testigenre5.parse(""); 
    assertEquals("From: Genre line: 114", "4|EDM|", testigenre5.toString()); 
    Genre testigenre6 = new Genre(); 
    testigenre6.parse("1|Pop|"); 
    assertEquals("From: Genre line: 117", "1|Pop|", testigenre6.toString()); 
  } // Generated by ComTest END
}