package bandbuddy.testit;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import bandbuddy.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.04.19 03:28:25 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class HenkiloJaGenreTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi101 */
  @Test
  public void testRekisteroi101() {    // HenkiloJaGenre: 101
    HenkiloJaGenre testilinkki1 = new HenkiloJaGenre(1); 
    testilinkki1.rekisteroi(); 
    assertEquals("From: HenkiloJaGenre line: 104", 1, testilinkki1.getTunnusNro()); 
    HenkiloJaGenre testilinkki2 = new HenkiloJaGenre(1); 
    testilinkki2.rekisteroi(); 
    assertEquals("From: HenkiloJaGenre line: 107", 2, testilinkki2.getTunnusNro()); 
  } // Generated by ComTest END
}