package bandbuddy.testit;
// Generated by ComTest BEGIN
import java.util.*;
import bandbuddy.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.04.19 17:44:34 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class HenkilotJaGenretTest {



  // Generated by ComTest BEGIN
  /** testHGenret56 */
  @Test
  public void testHGenret56() {    // HenkilotJaGenret: 56
    HenkilotJaGenret hi = new HenkilotJaGenret(); 
    HenkiloJaGenre a = new HenkiloJaGenre(1); hi.lisaa(a); 
    HenkiloJaGenre b = new HenkiloJaGenre(1); hi.lisaa(b); 
    HenkiloJaGenre c = new HenkiloJaGenre(2); hi.lisaa(c); 
    List<HenkiloJaGenre> kaikki; 
    kaikki = hi.hGenret(1); 
    assertEquals("From: HenkilotJaGenret line: 63", 2, kaikki.size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIterator102 */
  @Test
  public void testIterator102() {    // HenkilotJaGenret: 102
    HenkilotJaGenret hJG = new HenkilotJaGenret(); 
    HenkiloJaGenre a = new HenkiloJaGenre(); hJG.lisaa(a); 
    HenkiloJaGenre b = new HenkiloJaGenre(); hJG.lisaa(b); 
    HenkiloJaGenre c = new HenkiloJaGenre(); hJG.lisaa(c); 
    Iterator<HenkiloJaGenre> i2=hJG.iterator(); 
    assertEquals("From: HenkilotJaGenret line: 112", a, i2.next()); 
    assertEquals("From: HenkilotJaGenret line: 113", b, i2.next()); 
    assertEquals("From: HenkilotJaGenret line: 114", c, i2.next()); 
    try {
    assertEquals("From: HenkilotJaGenret line: 115", b, i2.next()); 
    fail("HenkilotJaGenret: 115 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}