package bandbuddy.testit;
// Generated by ComTest BEGIN
import fi.jyu.mit.ohj2.Suuntaaja.*;
import static org.junit.Assert.*;
import org.junit.*;
import bandbuddy.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.03.13 12:46:39 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class HenkiloTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi38 */
  @Test
  public void testRekisteroi38() {    // Henkilo: 38
    Henkilo testiHen1 = new Henkilo(); 
    assertEquals("From: Henkilo line: 40", 0, testiHen1.getId()); 
    testiHen1.rekisteroi(); 
    assertEquals("From: Henkilo line: 42", 1, testiHen1.getId()); 
    testiHen1.rekisteroi(); 
    assertEquals("From: Henkilo line: 44", 1, testiHen1.getId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTaytaValiaikaisetTiedot56 */
  @Test
  public void testTaytaValiaikaisetTiedot56() {    // Henkilo: 56
    StringOutput so = new StringOutput(); 
    Henkilo testiHen1 = new Henkilo(); 
    testiHen1.taytaValiaikaisetTiedot(); 
    testiHen1.tulosta(System.out); 
    String tulos =
    "-------------------------------------------------------------------\n" +
    "id: 0\n" +
    "nimi: Testijäbä Testinen\n" +
    "ikä: 20\n" +
    "sukupuoli: Mies\n" +
    "paikkakunta: Helsinki\n" +
    "vapaana: Viikonloppuisin\n" +
    "kokemus: 2 vuotta\n" +
    "yhteystiedot: 0401234567\n"; 
    assertEquals("From: Henkilo line: 72", null, so.ero(tulos)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetId91 */
  @Test
  public void testGetId91() {    // Henkilo: 91
    Henkilo testiHen1 = new Henkilo(); 
    assertEquals("From: Henkilo line: 93", 0, testiHen1.getId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNimi105 */
  @Test
  public void testGetNimi105() {    // Henkilo: 105
    Henkilo testiHen1 = new Henkilo(); 
    assertEquals("From: Henkilo line: 107", "", testiHen1.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetNimi119 */
  @Test
  public void testSetNimi119() {    // Henkilo: 119
    Henkilo testiHen1 = new Henkilo(); 
    testiHen1.setNimi("Aapo"); 
    assertEquals("From: Henkilo line: 122", "Aapo", testiHen1.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetIka134 */
  @Test
  public void testGetIka134() {    // Henkilo: 134
    Henkilo testiHen1 = new Henkilo(); 
    assertEquals("From: Henkilo line: 136", 0, testiHen1.getIka()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetIka148 */
  @Test
  public void testSetIka148() {    // Henkilo: 148
    Henkilo testiHen1 = new Henkilo(); 
    testiHen1.setIka(25); 
    assertEquals("From: Henkilo line: 151", 25, testiHen1.getIka()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetSukupuoli163 */
  @Test
  public void testGetSukupuoli163() {    // Henkilo: 163
    Henkilo testiHen1 = new Henkilo(); 
    assertEquals("From: Henkilo line: 165", "", testiHen1.getSukupuoli()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetSukupuoli177 */
  @Test
  public void testSetSukupuoli177() {    // Henkilo: 177
    Henkilo testiHen1 = new Henkilo(); 
    testiHen1.setSukupuoli("Mies"); 
    assertEquals("From: Henkilo line: 180", "Mies", testiHen1.getSukupuoli()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetPaikkakunta192 */
  @Test
  public void testGetPaikkakunta192() {    // Henkilo: 192
    Henkilo testiHen1 = new Henkilo(); 
    assertEquals("From: Henkilo line: 194", "", testiHen1.getPaikkakunta()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetPaikkakunta206 */
  @Test
  public void testSetPaikkakunta206() {    // Henkilo: 206
    Henkilo testiHen1 = new Henkilo(); 
    testiHen1.setPaikkakunta("Pieksämäki"); 
    assertEquals("From: Henkilo line: 209", "Pieksämäki", testiHen1.getPaikkakunta()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetVapaana220 */
  @Test
  public void testGetVapaana220() {    // Henkilo: 220
    Henkilo testiHen1 = new Henkilo(); 
    assertEquals("From: Henkilo line: 222", "", testiHen1.getVapaana()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetVapaana233 */
  @Test
  public void testSetVapaana233() {    // Henkilo: 233
    Henkilo testiHen1 = new Henkilo(); 
    testiHen1.setVapaana("Nyt"); 
    assertEquals("From: Henkilo line: 236", "Nyt", testiHen1.getVapaana()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKokemus247 */
  @Test
  public void testGetKokemus247() {    // Henkilo: 247
    Henkilo testiHen1 = new Henkilo(); 
    assertEquals("From: Henkilo line: 249", "", testiHen1.getKokemus()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetKokemus260 */
  @Test
  public void testSetKokemus260() {    // Henkilo: 260
    Henkilo testiHen1 = new Henkilo(); 
    testiHen1.setKokemus("Puoli vuotta"); 
    assertEquals("From: Henkilo line: 263", "Puoli vuotta", testiHen1.getKokemus()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetYhteystiedot274 */
  @Test
  public void testGetYhteystiedot274() {    // Henkilo: 274
    Henkilo testiHen1 = new Henkilo(); 
    assertEquals("From: Henkilo line: 276", "", testiHen1.getYhteystiedot()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetYhteystiedot287 */
  @Test
  public void testSetYhteystiedot287() {    // Henkilo: 287
    Henkilo testiHen1 = new Henkilo(); 
    testiHen1.setYhteystiedot("040XXXXXXX"); 
    assertEquals("From: Henkilo line: 290", "040XXXXXXX", testiHen1.getYhteystiedot()); 
  } // Generated by ComTest END
}