package bandbuddy.testit;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import bandbuddy.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.03.13 13:26:39 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class HenkilotTest {



  // Generated by ComTest BEGIN
  /** testGetLkm30 */
  @Test
  public void testGetLkm30() {    // Henkilot: 30
    Henkilot testiTaulukko1 = new Henkilot(); 
    assertEquals("From: Henkilot line: 32", 0, testiTaulukko1.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKokoLkm44 */
  @Test
  public void testGetKokoLkm44() {    // Henkilot: 44
    Henkilot testiTaulukko1 = new Henkilot(); 
    assertEquals("From: Henkilot line: 46", 5, testiTaulukko1.getKokoLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa58 */
  @Test
  public void testLisaa58() {    // Henkilot: 58
    Henkilot testiTaulukko1 = new Henkilot(); 
    assertEquals("From: Henkilot line: 60", 0, testiTaulukko1.getLkm()); 
    Henkilo perusPate = new Henkilo(); 
    perusPate.rekisteroi(); 
    testiTaulukko1.lisaa(perusPate); 
    assertEquals("From: Henkilot line: 64", 1, testiTaulukko1.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetHenkilo79 */
  @Test
  public void testGetHenkilo79() {    // Henkilot: 79
    Henkilot testiTaulukko1 = new Henkilot(); 
    Henkilo perusPate = new Henkilo(); 
    perusPate.rekisteroi(); 
    perusPate.setNimi("Perus-Pate"); 
    Henkilo akuAnkka = new Henkilo(); 
    akuAnkka.rekisteroi(); 
    akuAnkka.setNimi("Aku Ankka"); 
    Henkilo sepi = new Henkilo(); 
    sepi.rekisteroi(); 
    sepi.setNimi("Sepi"); 
    Henkilo eiLisattu = new Henkilo(); 
    eiLisattu.rekisteroi(); 
    testiTaulukko1.lisaa(perusPate); 
    testiTaulukko1.lisaa(akuAnkka); 
    testiTaulukko1.lisaa(sepi); 
    assertEquals("From: Henkilot line: 95", "Sepi", testiTaulukko1.getHenkilo(2).getNimi()); 
    assertEquals("From: Henkilot line: 96", "Aku Ankka", testiTaulukko1.getHenkilo(1).getNimi()); 
    assertEquals("From: Henkilot line: 97", "Perus-Pate", testiTaulukko1.getHenkilo(0).getNimi()); 
    try {
    assertEquals("From: Henkilot line: 98", eiLisattu, testiTaulukko1.getHenkilo(4)); 
    fail("Henkilot: 98 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    try {
    assertEquals("From: Henkilot line: 99", eiLisattu, testiTaulukko1.getHenkilo(5)); 
    fail("Henkilot: 99 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    try {
    assertEquals("From: Henkilot line: 100", eiLisattu, testiTaulukko1.getHenkilo(10)); 
    fail("Henkilot: 100 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}