package bandbuddy.testit;
// Generated by ComTest BEGIN
import java.io.IOException;
import fi.jyu.mit.ohj2.VertaaTiedosto;
import static org.junit.Assert.*;
import org.junit.*;
import bandbuddy.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.04.19 17:13:11 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class HenkilotTest {



  // Generated by ComTest BEGIN
  /** testGetLkm40 */
  @Test
  public void testGetLkm40() {    // Henkilot: 40
    Henkilot testiTaulukko1 = new Henkilot(); 
    assertEquals("From: Henkilot line: 42", 0, testiTaulukko1.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKokoLkm54 */
  @Test
  public void testGetKokoLkm54() {    // Henkilot: 54
    Henkilot testiTaulukko1 = new Henkilot(); 
    assertEquals("From: Henkilot line: 56", 5, testiTaulukko1.getKokoLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa76 */
  @Test
  public void testLisaa76() {    // Henkilot: 76
    Henkilot testiTaulukko1 = new Henkilot(); 
    assertEquals("From: Henkilot line: 78", 0, testiTaulukko1.getLkm()); 
    Henkilo perusPate = new Henkilo(); 
    perusPate.rekisteroi(); 
    testiTaulukko1.lisaa(perusPate); 
    assertEquals("From: Henkilot line: 82", 1, testiTaulukko1.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetHenkilo98 */
  @Test
  public void testGetHenkilo98() {    // Henkilot: 98
    Henkilot testiTaulukko1 = new Henkilot(); 
    Henkilo perusPate = new Henkilo(); 
    perusPate.rekisteroi(); 
    perusPate.setNimi("Perus-Pate"); 
    Henkilo akuAnkka = new Henkilo(); 
    akuAnkka.rekisteroi(); 
    akuAnkka.setNimi("Aku Ankka"); 
    Henkilo sepi = new Henkilo(); 
    sepi.rekisteroi(); 
    sepi.setNimi("Sepi"); 
    Henkilo eiLisattu = new Henkilo(); 
    eiLisattu.rekisteroi(); 
    testiTaulukko1.lisaa(perusPate); 
    testiTaulukko1.lisaa(akuAnkka); 
    testiTaulukko1.lisaa(sepi); 
    assertEquals("From: Henkilot line: 114", "Sepi", testiTaulukko1.getHenkilo(2).getNimi()); 
    assertEquals("From: Henkilot line: 115", "Aku Ankka", testiTaulukko1.getHenkilo(1).getNimi()); 
    assertEquals("From: Henkilot line: 116", "Perus-Pate", testiTaulukko1.getHenkilo(0).getNimi()); 
    try {
    assertEquals("From: Henkilot line: 117", eiLisattu, testiTaulukko1.getHenkilo(4)); 
    fail("Henkilot: 117 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    try {
    assertEquals("From: Henkilot line: 118", eiLisattu, testiTaulukko1.getHenkilo(5)); 
    fail("Henkilot: 118 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    try {
    assertEquals("From: Henkilot line: 119", eiLisattu, testiTaulukko1.getHenkilo(10)); 
    fail("Henkilot: 119 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta181 
   * @throws IOException when error
   */
  @Test
  public void testLueTiedostosta181() throws IOException {    // Henkilot: 181
    VertaaTiedosto.kirjoitaTiedosto("testi.dat", ";id|nimi|ika|sukupuoli|paikkakunta|vapaana|kokemus|yhteystiedot\n1|Erkki Esim|13|Mies|Hesa|viikonloppuisin|5v|040xxx\n2|Iso boi|26|Mies|Hesa|viikonloppuisin|10v|040xxx|"); 
    Henkilot testiHenkilotLuokka = new Henkilot(); 
    testiHenkilotLuokka.setLuettavaTiedosto("testi.dat"); 
    testiHenkilotLuokka.lueTiedostosta(); 
    VertaaTiedosto.tuhoaTiedosto("testi.dat"); 
    assertEquals("From: Henkilot line: 190", 2, testiHenkilotLuokka.getLkm()); 
    assertEquals("From: Henkilot line: 191", "1|Erkki Esim|13|Mies|Hesa|viikonloppuisin|5v|040xxx|", testiHenkilotLuokka.getHenkilo(0).toString()); 
    assertEquals("From: Henkilot line: 192", "2|Iso boi|26|Mies|Hesa|viikonloppuisin|10v|040xxx|", testiHenkilotLuokka.getHenkilo(1).toString()); 
  } // Generated by ComTest END
}