package bandbuddy.testit;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import bandbuddy.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.04.18 22:51:56 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class HenkiloJaInstrumenttiTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi99 */
  @Test
  public void testRekisteroi99() {    // HenkiloJaInstrumentti: 99
    HenkiloJaInstrumentti soittaja= new HenkiloJaInstrumentti(1); 
    soittaja.rekisteroi(); 
    assertEquals("From: HenkiloJaInstrumentti line: 102", 1, soittaja.getTunnusNro()); 
    HenkiloJaInstrumentti soittaja2= new HenkiloJaInstrumentti(1); 
    soittaja2.rekisteroi(); 
    assertEquals("From: HenkiloJaInstrumentti line: 105", 2, soittaja2.getTunnusNro()); 
  } // Generated by ComTest END
}