package bandbuddy.testit;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import bandbuddy.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.04.20 09:15:29 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class HenkiloJaInstrumenttiTest {



  // Generated by ComTest BEGIN
  /** testParse95 */
  @Test
  public void testParse95() {    // HenkiloJaInstrumentti: 95
    HenkiloJaInstrumentti testialkio1 = new HenkiloJaInstrumentti(3, 7); 
    assertEquals("From: HenkiloJaInstrumentti line: 97", 3, testialkio1.getHenkilonNro()); 
    assertEquals("From: HenkiloJaInstrumentti line: 98", 7, testialkio1.getInstrumentinNro()); 
    assertEquals("From: HenkiloJaInstrumentti line: 99", "3|7|", testialkio1.toString()); 
    testialkio1.parse("11|2|"); 
    assertEquals("From: HenkiloJaInstrumentti line: 101", 11, testialkio1.getHenkilonNro()); 
    assertEquals("From: HenkiloJaInstrumentti line: 102", 2, testialkio1.getInstrumentinNro()); 
  } // Generated by ComTest END
}