package bandbuddy.testit;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import bandbuddy.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.04.18 23:18:10 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class HenkilotJaGenretTest {



  // Generated by ComTest BEGIN
  /** testHGenret57 */
  @Test
  public void testHGenret57() {    // HenkilotJaGenret: 57
    HenkilotJaGenret hi = new HenkilotJaGenret(); 
    HenkiloJaGenre a = new HenkiloJaGenre(1); hi.lisaa(a); 
    HenkiloJaGenre b = new HenkiloJaGenre(1); hi.lisaa(b); 
    HenkiloJaGenre c = new HenkiloJaGenre(2); hi.lisaa(c); 
    List<HenkiloJaGenre> kaikki; 
    kaikki = hi.hGenret(1); 
    assertEquals("From: HenkilotJaGenret line: 64", 2, kaikki.size()); 
  } // Generated by ComTest END
}