package bandbuddy.testit;
// Generated by ComTest BEGIN
import java.util.*;
import bandbuddy.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.04.19 17:42:25 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class HenkilotJaInstrumentitTest {



  // Generated by ComTest BEGIN
  /** testSoittimet57 */
  @Test
  public void testSoittimet57() {    // HenkilotJaInstrumentit: 57
    HenkilotJaInstrumentit hi = new HenkilotJaInstrumentit(); 
    HenkiloJaInstrumentti a = new HenkiloJaInstrumentti(1); hi.lisaa(a); 
    HenkiloJaInstrumentti b = new HenkiloJaInstrumentti(1); hi.lisaa(b); 
    HenkiloJaInstrumentti c = new HenkiloJaInstrumentti(2); hi.lisaa(c); 
    List<HenkiloJaInstrumentti> kaikki; 
    kaikki = hi.soittimet(1); 
    assertEquals("From: HenkilotJaInstrumentit line: 64", 2, kaikki.size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIterator103 */
  @Test
  public void testIterator103() {    // HenkilotJaInstrumentit: 103
    HenkilotJaInstrumentit hJI = new HenkilotJaInstrumentit(); 
    HenkiloJaInstrumentti a = new HenkiloJaInstrumentti(); hJI.lisaa(a); 
    HenkiloJaInstrumentti b = new HenkiloJaInstrumentti(); hJI.lisaa(b); 
    HenkiloJaInstrumentti c = new HenkiloJaInstrumentti(); hJI.lisaa(c); 
    Iterator<HenkiloJaInstrumentti> i2=hJI.iterator(); 
    assertEquals("From: HenkilotJaInstrumentit line: 113", a, i2.next()); 
    assertEquals("From: HenkilotJaInstrumentit line: 114", b, i2.next()); 
    assertEquals("From: HenkilotJaInstrumentit line: 115", c, i2.next()); 
    try {
    assertEquals("From: HenkilotJaInstrumentit line: 116", b, i2.next()); 
    fail("HenkilotJaInstrumentit: 116 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}