package bandbuddy.testit;
// Generated by ComTest BEGIN
import fi.jyu.mit.ohj2.Suuntaaja.*;
import static org.junit.Assert.*;
import org.junit.*;
import bandbuddy.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.04.19 22:34:16 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class HenkiloTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi37 */
  @Test
  public void testRekisteroi37() {    // Henkilo: 37
    Henkilo testiHen1 = new Henkilo(); 
    assertEquals("From: Henkilo line: 39", 0, testiHen1.getId()); 
    testiHen1.rekisteroi(); 
    assertEquals("From: Henkilo line: 41", 1, testiHen1.getId()); 
    testiHen1.rekisteroi(); 
    assertEquals("From: Henkilo line: 43", 1, testiHen1.getId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTaytaValiaikaisetTiedot68 */
  @Test
  public void testTaytaValiaikaisetTiedot68() {    // Henkilo: 68
    StringOutput so = new StringOutput(); 
    Henkilo testiHen1 = new Henkilo(); 
    testiHen1.taytaValiaikaisetTiedot(); 
    testiHen1.tulosta(System.out); 
    String tulos =
    "-------------------------------------------------------------------\n" +
    "id: 0\n" +
    "nimi: Testijäbä Testinen\n" +
    "ikä: 20\n" +
    "sukupuoli: Mies\n" +
    "paikkakunta: Helsinki\n" +
    "vapaana: Viikonloppuisin\n" +
    "kokemus: 2 vuotta\n" +
    "yhteystiedot: 0401234567\n"; 
    assertEquals("From: Henkilo line: 84", null, so.ero(tulos)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetId103 */
  @Test
  public void testGetId103() {    // Henkilo: 103
    Henkilo testiHen1 = new Henkilo(); 
    assertEquals("From: Henkilo line: 105", 0, testiHen1.getId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNimi117 */
  @Test
  public void testGetNimi117() {    // Henkilo: 117
    Henkilo testiHen1 = new Henkilo(); 
    assertEquals("From: Henkilo line: 119", "", testiHen1.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetNimi131 */
  @Test
  public void testSetNimi131() {    // Henkilo: 131
    Henkilo testiHen1 = new Henkilo(); 
    testiHen1.setNimi("Aapo"); 
    assertEquals("From: Henkilo line: 134", "Aapo", testiHen1.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetIka146 */
  @Test
  public void testGetIka146() {    // Henkilo: 146
    Henkilo testiHen1 = new Henkilo(); 
    assertEquals("From: Henkilo line: 148", 0, testiHen1.getIka()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetIka160 */
  @Test
  public void testSetIka160() {    // Henkilo: 160
    Henkilo testiHen1 = new Henkilo(); 
    testiHen1.setIka(25); 
    assertEquals("From: Henkilo line: 163", 25, testiHen1.getIka()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetSukupuoli175 */
  @Test
  public void testGetSukupuoli175() {    // Henkilo: 175
    Henkilo testiHen1 = new Henkilo(); 
    assertEquals("From: Henkilo line: 177", "", testiHen1.getSukupuoli()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetSukupuoli189 */
  @Test
  public void testSetSukupuoli189() {    // Henkilo: 189
    Henkilo testiHen1 = new Henkilo(); 
    testiHen1.setSukupuoli("Mies"); 
    assertEquals("From: Henkilo line: 192", "Mies", testiHen1.getSukupuoli()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetPaikkakunta204 */
  @Test
  public void testGetPaikkakunta204() {    // Henkilo: 204
    Henkilo testiHen1 = new Henkilo(); 
    assertEquals("From: Henkilo line: 206", "", testiHen1.getPaikkakunta()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetPaikkakunta218 */
  @Test
  public void testSetPaikkakunta218() {    // Henkilo: 218
    Henkilo testiHen1 = new Henkilo(); 
    testiHen1.setPaikkakunta("Pieksämäki"); 
    assertEquals("From: Henkilo line: 221", "Pieksämäki", testiHen1.getPaikkakunta()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetVapaana232 */
  @Test
  public void testGetVapaana232() {    // Henkilo: 232
    Henkilo testiHen1 = new Henkilo(); 
    assertEquals("From: Henkilo line: 234", "", testiHen1.getVapaana()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetVapaana245 */
  @Test
  public void testSetVapaana245() {    // Henkilo: 245
    Henkilo testiHen1 = new Henkilo(); 
    testiHen1.setVapaana("Nyt"); 
    assertEquals("From: Henkilo line: 248", "Nyt", testiHen1.getVapaana()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKokemus259 */
  @Test
  public void testGetKokemus259() {    // Henkilo: 259
    Henkilo testiHen1 = new Henkilo(); 
    assertEquals("From: Henkilo line: 261", "", testiHen1.getKokemus()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetKokemus272 */
  @Test
  public void testSetKokemus272() {    // Henkilo: 272
    Henkilo testiHen1 = new Henkilo(); 
    testiHen1.setKokemus("Puoli vuotta"); 
    assertEquals("From: Henkilo line: 275", "Puoli vuotta", testiHen1.getKokemus()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetYhteystiedot286 */
  @Test
  public void testGetYhteystiedot286() {    // Henkilo: 286
    Henkilo testiHen1 = new Henkilo(); 
    assertEquals("From: Henkilo line: 288", "", testiHen1.getYhteystiedot()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetYhteystiedot299 */
  @Test
  public void testSetYhteystiedot299() {    // Henkilo: 299
    Henkilo testiHen1 = new Henkilo(); 
    testiHen1.setYhteystiedot("040XXXXXXX"); 
    assertEquals("From: Henkilo line: 302", "040XXXXXXX", testiHen1.getYhteystiedot()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse349 */
  @Test
  public void testParse349() {    // Henkilo: 349
    Henkilo testiHenkilo1 = new Henkilo(); 
    testiHenkilo1.parse("1|Roope Ankka|50|Mies|Ankkalinna|Iltaisin|10v|0401234567|"); 
    assertEquals("From: Henkilo line: 352", "1|Roope Ankka|50|Mies|Ankkalinna|Iltaisin|10v|0401234567|", testiHenkilo1.toString()); 
    Henkilo testiHenkilo2 = new Henkilo(); 
    testiHenkilo2.parse(""); 
    assertEquals("From: Henkilo line: 355", "-1||-1||||||", testiHenkilo2.toString()); 
  } // Generated by ComTest END
}