package bandbuddy.testit;
// Generated by ComTest BEGIN
import java.util.*;
import fi.jyu.mit.ohj2.VertaaTiedosto;
import bandbuddy.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END
import java.io.IOException;

/**
 * Test class made by ComTest
 * @version 2018.04.19 17:31:05 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class InstrumentitTest {



  // Generated by ComTest BEGIN
  /** testSoitin61 */
  @Test
  public void testSoitin61() {    // Instrumentit: 61
    Instrumentit i = new Instrumentit(); 
    Instrumentti a = new Instrumentti("Kitara"); 
    a.rekisteroi(); 
    i.lisaa(a); 
    Instrumentti b = new Instrumentti("Rummut"); 
    b.rekisteroi(); 
    i.lisaa(b); 
    Instrumentti c = new Instrumentti("Basso"); 
    c.rekisteroi(); 
    i.lisaa(c); 
    assertEquals("From: Instrumentit line: 72", 3, i.getLkm()); 
    assertEquals("From: Instrumentit line: 73", "ei toimi", i.soitin(-1)); 
    assertEquals("From: Instrumentit line: 74", "Basso", i.soitin(3)); 
    assertEquals("From: Instrumentit line: 75", "Kitara", i.soitin(1)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta104 
   * @throws IOException when error
   */
  @Test
  public void testLueTiedostosta104() throws IOException {    // Instrumentit: 104
    VertaaTiedosto.kirjoitaTiedosto("testi.dat", ";nid|instrumentti|\n1|Sähkökitara|\n2|Sähköbasso|\n3|Oboe|\n4|Fagotti|\n5|Saksofoni|\n"); 
    Instrumentit testiInstrumentitLuokka = new Instrumentit(); 
    testiInstrumentitLuokka.setLuettavaTiedosto("testi.dat"); 
    testiInstrumentitLuokka.lueTiedostosta(); 
    VertaaTiedosto.tuhoaTiedosto("testi.dat"); 
    assertEquals("From: Instrumentit line: 113", 5, testiInstrumentitLuokka.getLkm()); 
    assertEquals("From: Instrumentit line: 114", "Sähkökitara", testiInstrumentitLuokka.soitin(1)); 
    assertEquals("From: Instrumentit line: 115", "Sähköbasso", testiInstrumentitLuokka.soitin(2)); 
    assertEquals("From: Instrumentit line: 116", "Oboe", testiInstrumentitLuokka.soitin(3)); 
    assertEquals("From: Instrumentit line: 117", "Fagotti", testiInstrumentitLuokka.soitin(4)); 
    assertEquals("From: Instrumentit line: 118", "Saksofoni", testiInstrumentitLuokka.soitin(5)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIterator167 */
  @Test
  public void testIterator167() {    // Instrumentit: 167
    Instrumentit soittimet = new Instrumentit(); 
    Instrumentti a = new Instrumentti("Kitara"); soittimet.lisaa(a); 
    Instrumentti b = new Instrumentti("Basso"); soittimet.lisaa(b); 
    Instrumentti c = new Instrumentti("Rummut"); soittimet.lisaa(c); 
    Iterator<Instrumentti> i2=soittimet.iterator(); 
    assertEquals("From: Instrumentit line: 177", a, i2.next()); 
    assertEquals("From: Instrumentit line: 178", b, i2.next()); 
    assertEquals("From: Instrumentit line: 179", c, i2.next()); 
    try {
    assertEquals("From: Instrumentit line: 180", b, i2.next()); 
    fail("Instrumentit: 180 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}