package bandbuddy.testit;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import bandbuddy.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.03.23 12:08:45 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class InstrumenttiTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi74 */
  @Test
  public void testRekisteroi74() {    // Instrumentti: 74
    Instrumentti testi = new Instrumentti("kitara"); 
    testi.rekisteroi(); 
    assertEquals("From: Instrumentti line: 77", 1, testi.getTunnusNro()); 
    Instrumentti testi1 = new Instrumentti("rummut"); 
    testi1.rekisteroi(); 
    assertEquals("From: Instrumentti line: 80", 2, testi1.getTunnusNro()); 
  } // Generated by ComTest END
}