package bandbuddy.testit;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import bandbuddy.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.04.18 22:55:23 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class InstrumenttiTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi62 */
  @Test
  public void testRekisteroi62() {    // Instrumentti: 62
    Instrumentti testisoitin1 = new Instrumentti("kitara"); 
    testisoitin1.rekisteroi(); 
    assertEquals("From: Instrumentti line: 65", 1, testisoitin1.getTunnusNro()); 
    Instrumentti testisoitin2 = new Instrumentti("rummut"); 
    testisoitin2.rekisteroi(); 
    assertEquals("From: Instrumentti line: 68", 2, testisoitin2.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString92 */
  @Test
  public void testToString92() {    // Instrumentti: 92
    Instrumentti testisoitin3 = new Instrumentti("kitara"); 
    testisoitin3.rekisteroi(); 
    assertEquals("From: Instrumentti line: 95", "3|kitara|", testisoitin3.toString()); 
    Instrumentti testisoitin4 = new Instrumentti(); 
    assertEquals("From: Instrumentti line: 97", "0||", testisoitin4.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse110 */
  @Test
  public void testParse110() {    // Instrumentti: 110
    Instrumentti testisoitin5 = new Instrumentti("Banjo"); 
    testisoitin5.rekisteroi(); 
    testisoitin5.parse(""); 
    assertEquals("From: Instrumentti line: 114", "4|Banjo|", testisoitin5.toString()); 
    Instrumentti testisoitin6 = new Instrumentti(); 
    testisoitin6.parse("1|Kitara|"); 
    assertEquals("From: Instrumentti line: 117", "1|Kitara|", testisoitin6.toString()); 
  } // Generated by ComTest END
}