package bandbuddy.testit;
// Generated by ComTest BEGIN
import java.util.*;
import fi.jyu.mit.ohj2.VertaaTiedosto;
import static org.junit.Assert.*;
import org.junit.*;
import bandbuddy.*;
// Generated by ComTest END
import java.io.IOException;

/**
 * Test class made by ComTest
 * @version 2018.04.18 22:59:48 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class InstrumentitTest {



  // Generated by ComTest BEGIN
  /** testSoitin61 */
  @Test
  public void testSoitin61() {    // Instrumentit: 61
    Instrumentit i = new Instrumentit(); 
    Instrumentti a = new Instrumentti("Kitara"); 
    a.rekisteroi(); 
    i.lisaa(a); 
    Instrumentti b = new Instrumentti("Rummut"); 
    b.rekisteroi(); 
    i.lisaa(b); 
    Instrumentti c = new Instrumentti("Basso"); 
    c.rekisteroi(); 
    i.lisaa(c); 
    assertEquals("From: Instrumentit line: 72", 3, i.getLkm()); 
    assertEquals("From: Instrumentit line: 73", "ei toimi", i.soitin(-1)); 
    assertEquals("From: Instrumentit line: 74", "Kitara", i.soitin(1)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta103 
   * @throws IOException when error
   */
  @Test
  public void testLueTiedostosta103() throws IOException {    // Instrumentit: 103
    VertaaTiedosto.kirjoitaTiedosto("testi.dat", ";nid|instrumentti|\n1|Sähkökitara|\n2|Sähköbasso|\n3|Oboe|\n4|Fagotti|\n5|Saksofoni|\n"); 
    Instrumentit testiInstrumentitLuokka = new Instrumentit(); 
    testiInstrumentitLuokka.setLuettavaTiedosto("testi.dat"); 
    testiInstrumentitLuokka.lueTiedostosta(); 
    VertaaTiedosto.tuhoaTiedosto("testi.dat"); 
    assertEquals("From: Instrumentit line: 112", 5, testiInstrumentitLuokka.getLkm()); 
    assertEquals("From: Instrumentit line: 113", "Sähkökitara", testiInstrumentitLuokka.soitin(1)); 
    assertEquals("From: Instrumentit line: 114", "Sähköbasso", testiInstrumentitLuokka.soitin(2)); 
    assertEquals("From: Instrumentit line: 115", "Oboe", testiInstrumentitLuokka.soitin(3)); 
    assertEquals("From: Instrumentit line: 116", "Fagotti", testiInstrumentitLuokka.soitin(4)); 
    assertEquals("From: Instrumentit line: 117", "Saksofoni", testiInstrumentitLuokka.soitin(5)); 
  } // Generated by ComTest END
}