package bandbuddy.testit;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import bandbuddy.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.03.23 13:03:01 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class InstrumentitTest {



  // Generated by ComTest BEGIN
  /** testSoitin49 */
  @Test
  public void testSoitin49() {    // Instrumentit: 49
    Instrumentit i = new Instrumentit(); 
    Instrumentti a = new Instrumentti("kitara"); a.rekisteroi(); i.lisaa(a); 
    Instrumentti b = new Instrumentti("rummut"); b.rekisteroi(); i.lisaa(b); 
    Instrumentti c = new Instrumentti("basso"); c.rekisteroi(); i.lisaa(c); 
    assertEquals("From: Instrumentit line: 54", "kitara", i.soitin(1)); 
    assertEquals("From: Instrumentit line: 55", "basso", i.soitin(3)); 
  } // Generated by ComTest END
}